name: SpicyQoL
version: 1.0.0
main: it.giospezia.spicyqol.SpicyQoL
api-version: "1.21"
author: Spicy

commands:
  spawn: { description: Teleport allo spawn }
  setspawn: { description: Imposta lo spawn }
  home: { description: Teleport a una home }
  sethome: { description: Imposta una home }
  delhome: { description: Elimina una home }
  homes: { description: Lista home }
  tpa: { description: Richiesta di teleport }
  tpaccept: { description: Accetta richiesta }
  tpdeny: { description: Rifiuta richiesta }
  back: { description: Torna all'ultima posizione }
  rtp: { description: Teleporto random }
  ping: { description: Mostra il ping }
  tpamenu: { description: Apre la GUI TPA (accetta/rifiuta) }
  qol:
    description: Help SpicyQoL
    aliases: [spicyqol, spicyqolhelp, qolhelp]

permissions:
  spicyqol.setspawn:
    default: op
  spicyqol.spawn:
    default: true
  spicyqol.home:
    default: true
  spicyqol.sethome:
    default: true
  spicyqol.delhome:
    default: true
  spicyqol.homes:
    default: true
  spicyqol.tpa:
    default: true
  spicyqol.back:
    default: true
  spicyqol.rtp:
    default: true
  spicyqol.ping:
    default: true